### ISSUE TITLE
Groovy cannot load UnixSshFileSystem, but identical java code does

### ISSUE THREAD

**Issue by sarnobat** [lucastheisen/jsch-nio#14]
I'm using the jsch-nio library in a groovy script where I copy the quick and dirty code from the front page into a .groovy file (no groovy syntax), but only the "jar" and "file" file systems are loaded. 

java.nio.file.ProviderNotFoundException: Provider "ssh.unix" not found
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:337)
        at java.nio.file.FileSystems.newFileSystem(FileSystems.java:272)
        at java_nio_file_FileSystems$newFileSystem.call(Unknown Source)

I don't know the subtleties of dynamic class loading but I've never had this problem with other Groovy scripts of mine. Do you have any suggestions how I can work around this issue? I tried creating a jar-with-dependencies via maven but that didn't help.

I really hope I can use this library. I expect it to make my app much better if I can integrate it.

**Comment by lucastheisen** [comment]
This is not a bug, but as you suspected, has to do with the way classes are loaded.  I added an example to the [README](https://github.com/lucastheisen/jsch-nio#groovy-example) that goes over the requirements to use with groovy.  Let me know if you have any further issues.

**Comment by sarnobat** [comment]
Thanks for the quick reply. That did indeed work.
