### ISSUE TITLE
UnixSshFileSystem.getPath("/") returns empty Path

### ISSUE THREAD

**Issue by meshcow** [lucastheisen/jsch-nio#15]
To demonstrate what I mean, the code 
```java
DefaultSessionFactory defaultSessionFactory = new DefaultSessionFactory( username, hostname, port );
environment.put( "defaultSessionFactory", defaultSessionFactory );
String rootPath="/";
URI uri = new URI( scheme + "://" + username + "@" + hostname + ":" + port + rootPath+"tmp/" );
System.out.println(uri);
FileSystem fileSystem = FileSystems.newFileSystem( uri, environment );
System.out.println("path: "+fileSystem.getPath(rootPath));
System.out.println("path: "+fileSystem.getPath(rootPath).toAbsolutePath());
System.out.println("path: "+fileSystem.getPath("aaa"));
System.out.println("path: "+fileSystem.getPath("aaa").toAbsolutePath());
System.out.println("path: "+fileSystem.getPath(rootPath + "aaa"));
System.out.println("path: "+fileSystem.getPath(rootPath+"aaa").toAbsolutePath());
```
prints the following:
```bash
ssh.unix://me@127.0.0.1:22/tmp/
path: 
path: 
path: aaa
path: /tmp/aaa
path: /aaa
path: /aaa
```
The same behaviour is if the source URI is of the form "ssh.unix://username@host:port/" (path=/).
It is a bit misleading as Files.exists() on these returned empty paths returns false, however those input paths do exist.
Is there any specific reason for that working this way? I've tried sun.nio.fs.MacOSXFileSystem, its getPath("/") returns "/", I suspect Linux/Unix ones do the same.  

To workaround it, I am currently using  fileSystem.getPath("/."), then it works correctly for accessing remote files whose paths get resolved via such root path, although looks ugly.

**Comment by lucastheisen** [comment]
I agree that the `toString` was printing out an _incorrect_ value.  I fixed that.  However, i was unable to reproduce your problems with exists.  I added two new unit tests: [testExists()](https://github.com/lucastheisen/jsch-nio/blob/master/src/test/java/com/pastdev/jsch/nio/file/UnixSshFileSystemTest.java#L96) and [testGetPath()](https://github.com/lucastheisen/jsch-nio/blob/master/src/test/java/com/pastdev/jsch/nio/file/UnixSshFileSystemTest.java#L108) to ensure proper behavior.

I also released a new version, 0.1.8 (it should appear on Maven Central as soon as Sonatype pushes it).

Give it a go and see if you are still experiencing problems.
