### ISSUE TITLE
Error creating directories when some parents already exists

### ISSUE THREAD

**Issue by gmishkin** [lucastheisen/jsch-nio#27]
I've seen errors with `Files.createDirectories()` if some of the parents already exist. Based on the [docs](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#createDirectories-java.nio.file.Path-java.nio.file.attribute.FileAttribute...-) it doesn't seem like it's supposed to throw an exception in this case.

Situations I've seen errors are
- The directory already exists
- One of the parent directories already exists
- The grandparent directory exists and the user doesn't have write permissions, but the parent directory exists and the user _does_ have write permissions

I think that to resolve these issues `mkdir --parents` could be used, but I'm not sure how portable that option is, and whether you can tell whether you are being called from `Files.createDirectories()` vs. something more strict like `createDirectory()`. So there may be a better solution here.

**Comment by lucastheisen** [comment]
I don't implement the `Files` class, just the `FileSystemProvider`.  Also, there is no way to tell which method the providers `createDirectory` is getting called from.  Given that the providers contract explicitly states:

> `IOException` - if an I/O error occurs or the *parent directory does not exist*

I don't think i can change anything here.  There may have been a bug in the version of java you are using...  Have you tried another version?

That said, this implementation does support command substitution via system properties, so you could configure `mkdir` to be `mkdir -p` for your instance...

**Comment by gmishkin** [comment]
Oh yeah I know you don’t implement Files but that’s interesting that the providers contract says you should throw an exception. I’ll check the code of the normal provider and see how it’s working there, and also try out the system property. Thanks for the pointer!
